# Generated by Django 4.0.1 on 2022-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battlefield1Stats',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('rank', models.BigIntegerField(db_column='Rank', primary_key=True, serialize=False)),
                ('gamer', models.TextField(blank=True, db_column='Gamer', null=True)),
                ('game_score', models.BigIntegerField(blank=True, db_column='Game Score', null=True)),
                ('games', models.BigIntegerField(blank=True, db_column='Games', null=True)),
                ('platform', models.TextField(blank=True, db_column='Platform', null=True)),
                ('original_platform', models.TextField(blank=True, db_column='Original Platform', null=True)),
                ('score_min', models.BigIntegerField(blank=True, db_column='Score/min', null=True)),
                ('kill_ratio', models.FloatField(blank=True, db_column='Kill Ratio', null=True)),
                ('win_percent', models.FloatField(blank=True, db_column='Win Percent', null=True)),
                ('btr_score', models.BigIntegerField(blank=True, db_column='BTR Score', null=True)),
                ('hours_played', models.FloatField(blank=True, db_column='Hours Played', null=True)),
                ('kills', models.BigIntegerField(blank=True, db_column='Kills', null=True)),
                ('deaths', models.BigIntegerField(blank=True, db_column='Deaths', null=True)),
                ('wins', models.BigIntegerField(blank=True, db_column='Wins', null=True)),
                ('losses', models.BigIntegerField(blank=True, db_column='Losses', null=True)),
                ('accuracy', models.FloatField(blank=True, db_column='Accuracy', null=True)),
                ('flags_captured', models.BigIntegerField(blank=True, db_column='Flags Captured', null=True)),
                ('flags_defended', models.BigIntegerField(blank=True, db_column='Flags Defended', null=True)),
                ('game_title', models.TextField(blank=True, db_column='Game Title', null=True)),
            ],
            options={
                'db_table': 'Battlefield1Stats',
                'managed': False,
            },
        ),
    ]
